version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build

      - unittest
      - run: dotnet test CircleCiDemo.Test/CircleCiDemo.Test.csproj 

      - publish
      - run: dotnet publish CircleCiDemo/CircleCiDemo.csproj -o ./publish

      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t danielmahadi/circleci-demo-docker:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push danielmahadi/circleci-demo-docker:$TAG